### ISSUE TITLE
Conda tab completion with conda for python 3.6?

### ISSUE THREAD

**Issue by mikeleonard** [conda/conda-docs#415]
Hi 

New to Conda. Just installed it. Conda python version is 3.6.

When I try to setup bash completion via https://conda.io/docs/install/tab-completion.html I get:
```bash
 - argcomplete -> argparse -> python 2.6* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

How can I resolve this? Thanks in advance.

**Comment by qiongsiwu** [comment]
I am running into the exact same problem on macOS.

**Comment by kalefranz** [comment]
After a lot of internal discussion, we've deprecated tab completion starting in conda 4.4.  I guess argcomplete also isn't built for python 3.6.  At some point in the future if we switch our python argparse for a better library, we can consider bringing back tab completion.

**Comment by grahamannett** [comment]
Hmm, this is a bit old (and I haven't used conda for awhile so not sure if this is common knowledge or better way for this, seems misleading to even have that in the docs still if its not supported on 3.6) but thought I'd comment.  
Argcomplete works fine with python3.6 atm but the official conda one is only built up to 3.5.  Im not sure why the official conda repo hasn't updated the argcomplete package but the conda-forge channel has a working one and works fine w/ 3.6.  @kalefranz seems like it would be straightforward and helpful to update either docs or the conda package itself

https://github.com/conda-forge/argcomplete-feedstock

**Comment by Snotzer** [comment]
Same problem here, the anaconda distributions with python 3.6+ do not have argcomplete included. We use a company wide installation here so it's not trivial to just add it back in.  All scripts use argcomplete so we have to stick with an older anaconda release... painful.

**Comment by niklasholm** [comment]
argcomplete is now available for python 3.6 in the official repositories (see ContinuumIO/anaconda-issues#7517), although tab completion for conda doesn't work for me. It seems to be loaded correctly, but typing `conda ins<tab>` doesn't do anything instead of completing to `conda install` as expected.

```shell
$ conda -V
conda 4.4.8
$ complete -p | grep -i conda
complete -o default -o nospace -F _python_argcomplete conda
```

Is tab completion now completely removed? If so, it should be clearly stated in the documention. It's quite annoying have a doc title saying "Enabling tab completion" and then finding out it doesn't work for some unexplained reason.

**Comment by Snotzer** [comment]
Yeah, I still have the same problem, I checked several versions of anaconda after version 4.0.0_py3 and none of them include argcomplete, (4.1.1_py3, 4.2.0_py3, 4.3.1_py3, 4.4.0_py3, 5.0.1_py3) very frustrating.

I thought it was a basic well used module. I don't see any replacement or discussion why it was removed. It's only 131KB...

**Comment by couzhei** [comment]
Same problem here! I just update my conda from 4.4.10 to 4.5.4, but the problem seems to be consistent. I'm running ubuntu 14.04 if that helps. However, in my case there doesn't seem to be any kind of problem, it simply does nothing!

**Comment by walkerh** [comment]
Apparently I'm not the only one who likes tab completion. I did this **hack**.

1. Installed argcomplete:
```
conda install --channel conda-forge argcomplete
activate-global-python-argcomplete 
```

2. Created an executable file named "tonda" (for tab-completing conda) in my `PATH` with these contents:
```
#!/anaconda3/anaconda/bin/python

# PYTHON_ARGCOMPLETE_OK

import re
import sys

import argcomplete

from conda.cli import main
from conda.cli.main import generate_parser

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    parser = generate_parser()
    argcomplete.autocomplete(parser)
    sys.exit(main())
```
You would need to use a shebang matching your anaconda or miniconda Python.

3. Added this to my `.bashrc`:
```
# Location generated by activate-global-python-argcomplete
source /usr/local/etc/bash_completion.d/python-argcomplete.sh
```
You would need to update the location in step 3 based on the output of step 1.

This **hack** depends on two **implementation details** of conda. The `generate_parser` function gives me an `argparse` parser that I can pass to `argcomplete.autocomplete`. After giving tab completion a chance to run, I just delegate to `conda.cli.main`, which is another implementation detail.

Read here to understand how `argcomplete` combines `argparse` and `bash` to automatically generate completions:

https://github.com/kislyuk/argcomplete

Since this is a **hack**, consider it good for a developer but **bad for production**.

**Comment by champnaman** [comment]
Guys, I am new to all this. So, please bear with my question. 

I am trying to enable tab completion as mentioned [here](https://conda.io/docs/user-guide/configuration/enable-tab-completion.html). But I don't exactly understand the what I need to do in the step 2.
![untitd](https://user-images.githubusercontent.com/5251592/46912940-9f2e3280-cf48-11e8-80a1-104021774709.png)

I tried to add this command to my .bashrc file, tried running this command in my bash shell, but nothing works. Could anyone help me out with this. It is really annoying to type the full name of the environments. Tab completion will help a lot. 

Thanks, 
Naman

**Comment by sungwonida** [comment]
I'm facing the same. (Tab completion not working)
