### ISSUE TITLE
Installation on Windows does not work

### ISSUE THREAD

**Issue by averri** [conda/conda-docs#507]
I have followed the documentation here: https://conda.io/docs/user-guide/install/windows.html

and after the installation the system can't find the 'conda' binary.

**Comment by averri** [comment]
It's a bit frustrating to see a installer like Conda failing to install itself.

**Comment by msarahan** [comment]
Are you using the Anaconda Prompt?  Since Anaconda 4.4, we no longer modify the PATH environment variable by default.  This is to avoid conflicts with other software.  As a consequence, conda doesn't work at a default cmd.exe prompt.  Anaconda Prompt is cmd.exe, but with the root Anaconda install environment activated.
