### ISSUE TITLE
Anaconda update error

### ISSUE THREAD

**Issue by matthiasstan** [conda/conda-docs#609]
Hi all,

I am new to Python and I've just installed Anaconda on my Mac (OS El Capitan). It seems, however, as if I cannot install any updates. Using commands in the Mac terminal like

```
conda update conda
conda update anaconda
conda update spyder
```

result in the following error:

> NotWritableError: The current user does not have write permissions to a required path.
>   path: /Users/stanglm/.conda/environments.txt
>   uid: 501
>   gid: 20
> 
> If you feel that permissions on this path are set incorrectly, you can manually
> change them by executing
> 
>   $ sudo chown 501:20 /Users/stanglm/.conda/environments.txt
> 
> In general, it's not advisable to use 'sudo conda'.

Also, if I try to update Spyder from the Anaconda-Navigator GUI, I get a similar error message.

If I execute the suggested command from above

`sudo chown 501:20 /Users/stanglm/.conda/environments.txt`

I get another error message:

> chown: /Users/stanglm/.conda/environments.txt: No such file or directory

The file environments.txt is not present.

Interestingly, I have installed Anaconda at the same time also on my Macbook (same operating system etc.), but here the file environments.txt is present and the updating works fine.

Does anyone know what I can do in order to update Conda/Anaconda/Spyder?

Thanks,
Matthias

**Comment by electronwill** [comment]
The best place to find help getting that install working is the Anaconda user forum: https://groups.google.com/a/anaconda.com/forum/#!forum/anaconda

(If it turns out to be some problem specific to conda, there is also a forum for that at https://groups.google.com/a/continuum.io/forum/#!forum/conda .)

I'm sorry only one of the two installs is working for you. I hope with the forum's help you can get the other working as well, and that you enjoy using Anaconda and Python!
