### ISSUE TITLE
lost tutorial: Building conda packages for general code projects

### ISSUE THREAD

**Issue by stas00** [conda/conda-docs#629]
What happened to: "Building conda packages for general code projects"?
https://github.com/conda/conda-docs/blob/15dabe242e58f93260497023313ad3d400a946f2/docs/source/build_tutorials/postgis.rst
Did it get lost in the shuffle? Or did you purposefully drop it? i.e. conda doesn't want any non-python projects anymore? Or were the details simply merged into the general docs?

Thanks.

**Comment by msarahan** [comment]
It was removed because way too much had changed and those instructions were no longer a helpful example.  Non-python projects are certainly of interest - that is one of conda's great strengths.  We just haven't had time to write better docs that actually work and won't get stale.  I think I've already pointed you to this, but this tutorial may be helpful: https://python-packaging-tutorial.readthedocs.io/en/latest/

**Comment by stas00** [comment]
Thank you for explaining what happened, @msarahan. I just couldn't derive from the file's history on github of why it was nulled w/o any comment - it happened during 'rewrite docs' commit. And the original was linked to from one of the stackoverflow questions being 404 so that's why I was trying to see where it disappeared.

And, yes, I have seen that tutorial. So I will edit that answer and explain what happened and add a link to https://python-packaging-tutorial.readthedocs.io/en/latest/binaries_dependencies.html instead.

Thank you.
