### ISSUE TITLE
macOS 10.9 SDK specifically, or most recent version?

### ISSUE THREAD

**Issue by kusanagee** [conda/conda-docs#651]
[Anaconda compiler tools documentation](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html) specifies that one must download and link macOS 10.9 SDK. Are/not more recent macOS SDKs supported?

**Comment by mingwandroid** [comment]
You can use any SDK you want, except for the most recent ones that use .tbd files, but there's no point in using a more recent SDK to build software that can be built just as well using an older SDK because you are then unnecessarily preventing people running old versions of macOS from running the software you built.

I know that the macOS SDKs claim to support some backwards compatibility with various flags and env. vars but I have found that to be far from the case in anything but the most simple scenarios.
