### ISSUE TITLE
Miniconda installer for Windows link is broken

### ISSUE THREAD

**Issue by mgrigore** [conda/conda-docs#654]
Accessing the link https://conda.io/miniconda.html gives the following message: This page does not exist yet.

**Comment by soapy1** [comment]
We are working on getting this back up. Until then, you can get the latest installers at https://repo.anaconda.com/miniconda

**Comment by dave559** [comment]
The link to https://conda.io/docs/user-guide/install/index.html 
from https://conda.io/en/latest/miniconda.html
also gives the same error (and similarly for various other documentation pages that I had linked to (I'm currently reviewing/updating our local information for end users about how to install/use Miniconda)).

Just wondering if the URIs are changing permanently, or if this is a temporary issue as per @soapy1's comment above?

**Comment by soapy1** [comment]
The URI's are changing permanently. Because of the change there are a few links that have been left dangling pointing to old urls. We are still working on fixing that bit. https://github.com/conda/conda-docs/pull/661 should fix the issue about links to  the installation guide from the miniconda page
