### ISSUE TITLE
Can't get to conda.io/docs

### ISSUE THREAD

**Issue by mbopfNIH** [conda/conda-docs#655]
Attempting to access the conda documentation via http:/conda.io/docs brings up the "Maze Found" error page: "Sorry this page does not exist yet". So pretty much all documentation is off-line.

**Comment by csoja** [comment]
Apologies for the inconvenience - the docs are currently being restructured.  You can find the conda and conda-build documentation here: https://conda.io/en/latest/

**Comment by epruesse** [comment]
The miniconda link https://conda.io/miniconda.html is also down.

**Comment by soapy1** [comment]
The docs should be all online now. They are in somewhat of a different form, separating out conda docs from conda-build docs. We've tried to add some redirects so that old book marks floating around don't get trashed. That being said, it is very possible that old urls will still lead to 404s. Most of what you are looking for is probably around here https://conda.io/projects/conda/en/latest/

**Comment by epruesse** [comment]
Thanks @soapy1
