### ISSUE TITLE
conda can not install pyside2

### ISSUE THREAD

**Issue by oldsiks** [conda/conda-docs#772]
Mac M1  can not install pyside2.

**Comment by chenghlee** [comment]
Neither conda-forge nor Anaconda has built a `pyside2` package for the Mac M1 (osx-arm64) platform:
```
$ CONDA_SUBDIR=osx-arm64 conda search -c conda-forge pyside2
Loading channels: done
No match found for: pyside2. Search: *pyside2*

PackagesNotFoundError: The following packages are not available from current channels:

  - pyside2

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
```

I suggest opening an [issue in the pyside2 feedstock](https://github.com/conda-forge/pyside2-feedstock/issues) so those maintainers can help you with this request.

Closing this issue since there's nothing the conda-docs team can do to (directly) address this issue.
