### ISSUE TITLE
Add contributing docs for how to use Sphinx and general documentation workflow

### ISSUE THREAD

**Issue by jezdez** [conda/conda-docs#818]

**Comment by emirkmo** [comment]
Just to give a head start, since I went through it as a first timer, it basically boiled down to:

 - installing the requirements, including all these extra sphinx related packages.
 - starting the sphinx web app from the terminal pointed to the right directory. 
 - making sure to edit the tocs to point to the new contribution if it’s not an update to an existing document.
 
 I think the list of requirements, The specific command for running the server,
And the warning about adding the contribution to the indexes is the minimum required documentation.
